### PR TITLE
keep docs snippets in sync with your code

### PR DESCRIPTION
**Pull request by SimonCropp**
not really valuable for the one snippet. but i assume you will eventually add more?

### CODE REVIEW

**Comment by khellang** [comment]
Wow, that's really nice! Thanks 👏🏻

**Review by khellang — APPROVED** [review]

**Comment by SimonCropp** [comment]
do u use gh actions ? https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/github-action.md

**Comment by khellang** [comment]
Thats awesome 😎 Added!

**Comment by SimonCropp** [comment]
and if u want an explorer extension https://github.com/SimonCropp/MarkdownSnippets#add-to-windows-explorer

**Pull request merged**
